name: Create Release of master branch

on:
  push:
    branches:
      - '*'

jobs:
  build:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Set env
        run: |
          echo "RELEASE_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "RELEASE_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build project
        run: bash ./build-spark.sh

      - name: Delete latest release
        uses: dev-drprasad/delete-tag-and-release@v0.1.3
        with:
          delete_release: true # default: false
          tag_name: ${{ env.RELEASE_BRANCH }}_latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ env.RELEASE_BRANCH }}_latest
          tag_name: ${{ env.RELEASE_BRANCH }}_latest
          body: release of ${{ env.RELEASE_BRANCH }} branch
          draft: false
          prerelease: false
          files: /tmp/opt/spark/spark-bin-hadoop-glue.tgz
